name: golangci-lint

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - 'LICENSE'
      - 'NOTICE'
      - 'PROJECT'
      - 'SECURITY_CONTACTS'

jobs:
  golangci:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Go 1.19.10
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.10

    - name: Checkout code
      uses: actions/checkout@v2

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.50.0
        skip-go-installation: true
